# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BitsBytes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BitsBytes
	pod 'Gigya'
	pod 'GigyaTfa'
	pod 'GigyaAuth'
	pod 'Firebase'
  	pod 'Firebase/Messaging'
  	pod 'FBSDKCoreKit'
  	pod 'FBSDKLoginKit'
  	pod 'GoogleSignIn'
  	pod 'LineSDKSwift'
end
