name: issue_created

on:
  issues:
    types:
      - opened
jobs:
  test-transition-issue:
    name: Open Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: CXCDC
        issuetype: Action
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.url }}
        fields: '{"team": "CDC Mobile"}'
    
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
