name:  swift mobile e2e failed
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  repository_dispatch:
    types: [trigger_event_from_tests_failed]

jobs:
  tests_done:
      runs-on: ubuntu-latest
      steps:
        - name: Mobile Test done
          run: echo "Failed"

        - name: Failed
          run: exit 1
